# Find and replace a string in your project files
name: Find and Replace
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "cloudwaitress"
          replace: "shepos"
